### ISSUE TITLE
When composer::project fails, it will stay half-installed

### ISSUE THREAD

**Issue by voidus** [tPl0ch/puppet-composer#35]
Subsequent calls to composer fail, because the directory already exists. It will not be run again either because it just checks if the directory exists.

**Comment by andyshinn** [comment]
I know this is a long outstanding bug. I posed a question about it here: http://stackoverflow.com/questions/27894095/how-to-get-puppet-exec-to-cleanup-directory-on-failure. Would it be sufficient to remove the directory on failure so subsequent runs will create it again?

**Comment by mcrumm** [comment]
So, this is the actual bug I was trying to fix when I started on the beaker config.  I didn't get a suitable test written, but the problem appears to be, at least in part, the `tries` parameter on the `exec` call.

AFAIK there's not currently a mechanism that will notify an exec on another exec's failed exit code.  This SO question explains it better than I can: http://stackoverflow.com/questions/25263746/puppet-how-to-use-the-exec-return-value-as-a-trigger

I would primarily encounter this bug when bumping up against GitHub rate limits, so the problem with the first answer proposed in your question is that you can't just `test -f ${project_dir}/composer.json`, because the install more than likely failed while downloading dependencies.

My $0.02 - The best solution was the first one you posed.  Running `create-project` in a temp path, then moving the directory to the real path on success, seems far more feasible than doing anything on failure.

**Comment by andyshinn** [comment]
The temporary folder idea seems to have the same problem. If it fails and the temporary directory is left there, subsequent runs will fail because the temp directory exists. Or maybe the first exec to the temporary directory is always 'forced' and then the mv only happens if the destination does not exist? Then the issue become the create project always run every Puppet run even when it doesn't have to. Such a silly issue with no simple way to solve it...

**Comment by mcrumm** [comment]
This might be a little far-fetched, but I was considering the possibility of using the suggested answer from SO, but using `test -f ${project_dir}/vendor/autoload.php` as the `unless` condition for the `rm` exec.

Composer generates its autoload files last, so the presence of `vendor/autoload.php` would indicate that all dependencies were downloaded properly.  An `exec` call to remove the directory unless the autoloader exists would need to be `refreshonly`, I believe, with a `notify` on the `create-project` exec, which, it appears, would still notify, even if the first exec fails (see http://projects.puppetlabs.com/issues/5876#note-16 and https://tickets.puppetlabs.com/browse/PUP-1106).

This "solution" would be rely on that bug in the refresh notifier, that will likely get closed by puppet 4.0.

If this seems remotely feasible to you, I'd be glad to start working on a beaker test. Otherwise, I'm afraid I'm out of clever thoughts.

**Comment by andyshinn** [comment]
I'd be more than happy to have you try out that solution. I think that gets it at least closer to recovering on a create-project failure.

**Comment by andyshinn** [comment]
The answer seems so simple now that I see it. Check out http://stackoverflow.com/a/27927163/684908. @mcrumm let me know if you want to try this out. Otherwise, I'll take a crack at it this weekend.

**Comment by mcrumm** [comment]
Wow, that does seem really simple! I'd be glad to give it a go.

**Comment by tPl0ch** [comment]
@mcrumm @andyshinn The fix from stackoverflow has been deployed and version 1.3.5 has been deployed to puppet forge.
